Awesome-Books-Refactor
tomdan-ai/Awesome-books-ES6 pull request #1
Opened 2023-03-27 17:24 UTC by tomdan-ai

### **Awesome books Documentation**

- [ ] Refactor JS to ES6 syntax
- [ ] Add an image to the website
- [ ] Made use of Arrow functions
- [ ] Avoid the use of the `var` keyword
- [ ] Add `let` and `const` keyword
- [ ] Added time and date with luxon package

2023-03-27 22:00 UTC, CollinsTatang reviewed
Hi @tomdan-ai, 

While you made a great effort in this project. Unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have a professional README file.

- [ ] Please make sure all main headers from the [README template](https://github.com/microverseinc/readme-template) should be present.
- [ ] Please make sure that you add the section **Future Features**, including 1-3 potential features to be added.
- [ ] Please fix the link to your license file, the current link is broken.


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-28 07:48 UTC, Shedrack-Sunday requested changes
Hi @tomdan-ai       👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done well implementing the requirements,  However, there are a few you need to work on, to move to the next project. 💯

 
![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights:
✔️ good code structure
✔️ good PR summary
✔️ Nice UI
  
# Required Changes ♻️

- [x] I must admit you have really put in the effort so far in this project, however, the changes required below need to be implemented :
- A few link issues and commented code to take care of👏


_check the comment section for a detailed review_ 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-03-28 07:48 UTC, Shedrack-Sunday commented on README.md
>  This project is [MIT](./LICENSE) licensed.
- [ ] You don't have this file at the root of your project, which makes your MIT link break. Either change it to the `MIT.md` on the root of your project or rename the `MIT.md` to `LICENSE`

2023-03-28 07:48 UTC, Shedrack-Sunday commented on index.html
> +      </button> -->
- [ ] Commented code should be removed from your code to avoid confusion and make the code base clean. Doing this often can lead to many codebases which will lead to bad code practice 👍

2023-03-28 08:25 UTC, Davidosky007 approved these changes
Hi @tomdan-ai 👋 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![approved-gif-gif](https://user-images.githubusercontent.com/52497246/228175268-5173dfd0-d132-4971-a2db-ec621132fd49.gif)
## Highlights
* No linter errors 👍 
* Good looking readme file 👍 
* Proper use of ES6 syntaxs 👍 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-28 08:26 UTC, merged